### ISSUE TITLE
Error running timer ‘git-ps1-mode-run-process’: (file-missing "Setting current directory" "No such file or directory"

### ISSUE THREAD

**Issue by juhp** [10sr/git-ps1-mode-el#5]
Thanks for git-ps1-mode-el: I really wanted this functionality in Emacs.

But I have a problem in the minibuffer with find-file I get errors appearing like:

```
Error running timer ‘git-ps1-mode-run-process’: (file-missing "Setting current directory" "No such file or directory" "/home/test/Downloads/Fedora-Workstation-Live-x86_64-2/") [2 times]
```

I guess git-ps1-mode-el should not be enabled in the minibuffer...
Can you add some instructions on how best to setup this minor mode?
Maybe it is easy to add a check to avoid the above problem.
(Actually I am kind of surprised that minibuffer find-file should trigger this mode.)

**Comment by 10sr** [comment]
Thanks for reporting! I'll look into it later.

**Comment by juhp** [comment]
I think removing `'force` helped, but I need to check/test more.

**Comment by 10sr** [comment]
Checking minibufferp seems to have already been implemented, so IMO that is the cause of this...
I found another potential bug that might be related with this issue, so I fixed it. ☝️ 
I want to see if it was fixed now.

**Comment by juhp** [comment]
Thanks looks good to me from initial testing :+1:
